#pragma once
//#include "stdafx.h"
#include <vtkObject.h>
#include <vtkObjectFactory.h>
#include <vtkRenderer.h>
#include <vtkSmartPointer.h>
#include <vtkCamera.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkCubeSource.h>
#include <vtkPolyDataMapper.h>
#include <vtkActor.h>
#include <memory>
#include <vtkInteractorStyleTrackballActor.h>
#include <vtkCommand.h>
#include <vtkTransform.h>
#include <vtkMatrix4x4.h>
#include <array>
#include <vtkProperty.h>
#include <vtkAxesActor.h>
#include <vtkTextProperty.h>
#include <vtkCaptionActor2D.h>
#include <vtkPropCollection.h>